#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Reproduce Figure 4 and the AMO-sensitivity supplementary figure.

This public script starts from compact time-series/source-data files rather
than the original gridded SODA/GODAS data. It performs:

1. Historical 21-year PDO/AMO low-frequency index construction.
2. Combination with the archived 10-year DL-PDO prediction.
3. Three AMO scenarios: persistence, damped persistence, recent linear trend.
4. GWI 21-year-window construction.
5. TCD_G projection using the manuscript regression coefficients.
6. Projection of the spring H and tau_x explained-variance contributions.
7. Figure 4 plotting and AMO-sensitivity plotting.
8. Export of source-data tables.

Year convention
---------------
All climate-index and TCD_G points in Figure 4 are labelled by the ENDING YEAR
of their 21-year window. Thus, for example, the point labelled 2026 represents
the 2006-2026 mean (conventional centered label: 2016).

Expected files
--------------
data/
├── pdo_index.1854-2025.nc
├── AMO_index_1854-2025.nc
├── future_10yr_pdo_prediction.csv
├── AMO_future_10yr_three_methods_wide.csv
├── global_warming_index_annual_raw.csv
├── GWI_future_10yr_recent30_quadratic_with_uncertainty.csv
└── Figure1_source_data.csv

`Figure1_source_data.csv` should contain the historical 21-year SODA-GODAS
diagnostics generated by the public Figure-1 analysis script, including:
    end_year
    TCD_G_mean_m
    contribution_H
    contribution_tau_x

The future PDO CSV should preferably contain:
    pdo_pred_mean, pdo_pred_p05, pdo_pred_p95,
    pdo_pred_member_1 ... pdo_pred_member_20

The AMO future CSV should contain:
    AMO_persistence
    AMO_damped_persistence
    AMO_recent_linear_trend

The GWI future CSV should contain:
    year, gwi_pred, gwi_p05, gwi_p95

Usage
-----
python figure4_analysis.py --data-dir data --output-dir outputs
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt
from scipy.signal import detrend


# =============================================================================
# Manuscript regression coefficients
# =============================================================================

# Warming-associated TCD_G component:
# TCD_G_warming = INTERCEPT_GWI + COEF_GWI * GWI_21yr
INTERCEPT_GWI = -74.45
COEF_GWI = -10.76

# Internal-variability TCD_G component:
# TCD_G_internal = INTERCEPT_INTERNAL
#                  + COEF_PDO * PDO(t)
#                  + COEF_AMO * AMO(t-8)
#                  + COEF_APJPT * APJPT(t-4)
INTERCEPT_INTERNAL = -0.97
COEF_PDO = 7.63
COEF_AMO = 0.23
COEF_APJPT = -1.32

# Relationship between TCD_G and spring ENSO precursor contributions.
# TCD_G is divided by 100 m, matching the Figure-1 regression scale.
INTERCEPT_H_ROLE = 1.97
COEF_H_ROLE = 2.07
INTERCEPT_TAUX_ROLE = -2.30
COEF_TAUX_ROLE = -3.50


# =============================================================================
# Fixed analysis settings
# =============================================================================

HIST_START_YEAR = 1920
HIST_END_YEAR = 2025
INDEX_FILE_START_YEAR = 1854
RUNNING_WINDOW = 21
FUTURE_YEARS = 10
GWI_REQUIRED_END_YEAR = 2035


def standardize(x: np.ndarray) -> np.ndarray:
    """Population-standardize a one-dimensional series, matching legacy code."""
    x = np.asarray(x, dtype=float)
    sd = np.nanstd(x, ddof=0)
    if not np.isfinite(sd) or sd == 0:
        raise ValueError("Cannot standardize a constant or invalid series.")
    return (x - np.nanmean(x)) / sd


def subset_monthly_by_index(
    values: np.ndarray,
    file_start_year: int,
    start_year: int,
    end_year: int,
) -> np.ndarray:
    """Extract monthly data using positional indexing only."""
    values = np.asarray(values, dtype=float).reshape(-1)
    i0 = (start_year - file_start_year) * 12
    i1 = (end_year - file_start_year + 1) * 12
    out = values[i0:i1]
    expected = (end_year - start_year + 1) * 12
    if len(out) != expected:
        raise ValueError(
            f"Extracted {len(out)} months, expected {expected}; "
            "check file start year and data length."
        )
    return out


def annual_mean(monthly: np.ndarray) -> np.ndarray:
    """Calendar-year mean from consecutive Jan-Dec monthly data."""
    monthly = np.asarray(monthly, dtype=float).reshape(-1)
    if len(monthly) % 12 != 0:
        raise ValueError("Monthly series length must be divisible by 12.")
    return np.nanmean(monthly.reshape(-1, 12), axis=1)


def forward_running_mean(annual: np.ndarray, window: int = 21) -> np.ndarray:
    """
    Forward 21-year mean used by the original Figure-4 plotting workflow.

    Element i is mean(annual[i:i+window]).
    Its natural Figure-4 label is the END year of that window.
    """
    annual = np.asarray(annual, dtype=float).reshape(-1)
    if len(annual) < window:
        raise ValueError("Series shorter than running-mean window.")
    return np.asarray(
        [np.nanmean(annual[i:i + window]) for i in range(len(annual) - window + 1)],
        dtype=float,
    )


def read_1d_variable(path: Path, variable: str) -> np.ndarray:
    """Read a 1-D index, accepting legacy singleton/EOF dimensions."""
    ds = xr.open_dataset(path, decode_times=False)
    if variable not in ds:
        raise KeyError(f"{path}: variable {variable!r} not found.")
    arr = np.asarray(ds[variable].values, dtype=float)
    arr = np.squeeze(arr)

    if arr.ndim == 1:
        return arr

    if arr.ndim == 2:
        # Retain compatibility with mode x time EOF-style files.
        return arr[0, :] if arr.shape[0] <= arr.shape[1] else arr[:, 0]

    raise ValueError(
        f"{path}: expected a 1-D or singleton/EOF-style 2-D variable, got {arr.shape}."
    )


def build_historical_low_frequency_indices(
    pdo_path: Path,
    amo_path: Path,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Reproduce historical PDO/AMO processing used by the legacy Figure-4 script.

    Monthly series -> linear detrend -> standardize -> annual mean -> forward
    21-year running mean.

    Returns
    -------
    window_end_years : ending years for all 21-year windows, 1940-2025
    pdo_rm21
    amo_rm21
    recent_end_years : 2016-2025
    """
    pdo = subset_monthly_by_index(
        read_1d_variable(pdo_path, "PDO_index"),
        INDEX_FILE_START_YEAR,
        HIST_START_YEAR,
        HIST_END_YEAR,
    )
    amo = subset_monthly_by_index(
        read_1d_variable(amo_path, "AMO_index"),
        INDEX_FILE_START_YEAR,
        HIST_START_YEAR,
        HIST_END_YEAR,
    )

    pdo = standardize(detrend(pdo))
    amo = standardize(detrend(amo))

    pdo_annual = annual_mean(pdo)
    amo_annual = annual_mean(amo)

    pdo_rm21 = forward_running_mean(pdo_annual, RUNNING_WINDOW)
    amo_rm21 = forward_running_mean(amo_annual, RUNNING_WINDOW)

    window_start_year = np.arange(
        HIST_START_YEAR,
        HIST_END_YEAR - RUNNING_WINDOW + 2,
        dtype=int,
    )
    window_end_year = window_start_year + RUNNING_WINDOW - 1

    return window_end_year, pdo_rm21, amo_rm21, window_end_year[-10:]


def read_pdo_future(path: Path) -> dict[str, np.ndarray]:
    """Read archived DL-PDO prediction and its ensemble spread."""
    df = pd.read_csv(path)

    if "pdo_pred_mean" in df:
        mean = df["pdo_pred_mean"].to_numpy(dtype=float)
    else:
        member_cols = [c for c in df.columns if c.startswith("pdo_pred_member_")]
        if not member_cols:
            raise ValueError(
                f"{path}: need 'pdo_pred_mean' or pdo_pred_member_* columns."
            )
        mean = np.nanmean(df[member_cols].to_numpy(dtype=float), axis=1)

    member_cols = [c for c in df.columns if c.startswith("pdo_pred_member_")]
    members = df[member_cols].to_numpy(dtype=float) if member_cols else None

    # Manuscript uncertainty convention: 5th-95th ensemble spread.
    if "pdo_pred_p05" in df and "pdo_pred_p95" in df:
        low = df["pdo_pred_p05"].to_numpy(dtype=float)
        high = df["pdo_pred_p95"].to_numpy(dtype=float)
    elif members is not None:
        low = np.nanpercentile(members, 5, axis=1)
        high = np.nanpercentile(members, 95, axis=1)
    else:
        raise ValueError(
            f"{path}: need pdo_pred_p05/p95 or member predictions for uncertainty."
        )

    if len(mean) != FUTURE_YEARS:
        raise ValueError(
            f"{path}: expected {FUTURE_YEARS} forecast rows, found {len(mean)}."
        )

    display_year = (
        df["display_year"].to_numpy(dtype=int)
        if "display_year" in df
        else np.arange(2026, 2026 + FUTURE_YEARS, dtype=int)
    )

    return {
        "mean": mean,
        "low": low,
        "high": high,
        "members": members,
        "display_year": display_year,
    }


def read_amo_future(path: Path) -> dict[str, np.ndarray]:
    """Read the three deterministic AMO scenarios."""
    df = pd.read_csv(path)
    required = [
        "AMO_persistence",
        "AMO_damped_persistence",
        "AMO_recent_linear_trend",
    ]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"{path}: missing columns {missing}")

    out = {
        "persistence": df["AMO_persistence"].to_numpy(dtype=float),
        "damped": df["AMO_damped_persistence"].to_numpy(dtype=float),
        "recent_trend": df["AMO_recent_linear_trend"].to_numpy(dtype=float),
    }
    for key, arr in out.items():
        if len(arr) != FUTURE_YEARS:
            raise ValueError(f"{path}: {key} has {len(arr)} rows; expected 10.")
    return out


def read_gwi_history(path: Path) -> tuple[np.ndarray, np.ndarray]:
    """Read annual GWI and retain 1996-2025 for the Figure-4 windows."""
    df = pd.read_csv(path)

    year_col = "year" if "year" in df else ("Year" if "Year" in df else df.columns[0])
    if "gwi" in df:
        value_col = "gwi"
    elif "global_warming_index" in df:
        value_col = "global_warming_index"
    else:
        value_col = df.columns[1]

    sub = df[(df[year_col] >= 1996) & (df[year_col] <= 2025)].copy()
    return (
        sub[year_col].to_numpy(dtype=int),
        sub[value_col].to_numpy(dtype=float),
    )


def read_gwi_future(path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Read annual projected GWI and 5th-95th uncertainty."""
    df = pd.read_csv(path)
    required = ["year", "gwi_pred", "gwi_p05", "gwi_p95"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"{path}: missing columns {missing}")
    return (
        df["year"].to_numpy(dtype=int),
        df["gwi_pred"].to_numpy(dtype=float),
        df["gwi_p05"].to_numpy(dtype=float),
        df["gwi_p95"].to_numpy(dtype=float),
    )


def complete_gwi_to_2035(
    hist_year: np.ndarray,
    hist_value: np.ndarray,
    future_year: np.ndarray,
    future_mean: np.ndarray,
    future_low: np.ndarray,
    future_high: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Complete the archived annual GWI projection through 2035 if necessary.

    The fallback preserves the original Figure-4 workflow: quadratic extension
    of the mean from the recent historical series, and quadratic extension of
    the archived lower/upper future bounds.
    """
    if np.nanmax(future_year) >= GWI_REQUIRED_END_YEAR:
        return future_year, future_mean, future_low, future_high

    missing_years = np.arange(
        int(np.nanmax(future_year)) + 1,
        GWI_REQUIRED_END_YEAR + 1,
        dtype=int,
    )

    coef_mean = np.polyfit(hist_year.astype(float), hist_value.astype(float), 2)
    coef_low = np.polyfit(future_year.astype(float), future_low.astype(float), 2)
    coef_high = np.polyfit(future_year.astype(float), future_high.astype(float), 2)

    return (
        np.append(future_year, missing_years),
        np.append(future_mean, np.polyval(coef_mean, missing_years)),
        np.append(future_low, np.polyval(coef_low, missing_years)),
        np.append(future_high, np.polyval(coef_high, missing_years)),
    )


def build_gwi_rm21(
    hist_year: np.ndarray,
    hist_value: np.ndarray,
    future_year: np.ndarray,
    future_mean: np.ndarray,
    future_low: np.ndarray,
    future_high: np.ndarray,
) -> dict[str, np.ndarray]:
    """Build 1996-2016 ... 2015-2035 GWI 21-year means."""
    future_year, future_mean, future_low, future_high = complete_gwi_to_2035(
        hist_year,
        hist_value,
        future_year,
        future_mean,
        future_low,
        future_high,
    )

    years = np.append(hist_year, future_year)
    mean = np.append(hist_value, future_mean)
    low = np.append(hist_value, future_low)
    high = np.append(hist_value, future_high)

    mean_map = dict(zip(years.astype(int), mean.astype(float)))
    low_map = dict(zip(years.astype(int), low.astype(float)))
    high_map = dict(zip(years.astype(int), high.astype(float)))

    rm_mean, rm_low, rm_high, window_end = [], [], [], []

    for start in range(1996, 2016):
        window = np.arange(start, start + RUNNING_WINDOW, dtype=int)
        missing = [year for year in window if year not in mean_map]
        if missing:
            raise ValueError(f"Incomplete GWI window; missing years {missing}")

        rm_mean.append(np.mean([mean_map[y] for y in window]))
        rm_low.append(np.mean([low_map[y] for y in window]))
        rm_high.append(np.mean([high_map[y] for y in window]))
        window_end.append(start + RUNNING_WINDOW - 1)

    return {
        "annual_year": years,
        "annual_mean": mean,
        "annual_low": low,
        "annual_high": high,
        "rm21_mean": np.asarray(rm_mean),
        "rm21_low": np.asarray(rm_low),
        "rm21_high": np.asarray(rm_high),
        "rm21_window_end": np.asarray(window_end, dtype=int),
    }


def read_historical_figure1_source(path: Path) -> pd.DataFrame:
    """
    Read the historical SODA-GODAS source data already used for Figure 1.

    This avoids redistributing or re-reading the legacy raw SODA2.2.4 fields.
    """
    df = pd.read_csv(path)
    required = [
        "end_year",
        "TCD_G_mean_m",
        "contribution_H",
        "contribution_tau_x",
    ]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"{path}: missing columns {missing}")

    out = df[(df["end_year"] >= 2000) & (df["end_year"] <= 2025)].copy()
    out = out.sort_values("end_year")
    return out


def calculate_projection(
    amo_combined: np.ndarray,
    pdo_hist_rm21: np.ndarray,
    amo_hist_rm21: np.ndarray,
    pdo_future: dict[str, np.ndarray],
    gwi_rm21: dict[str, np.ndarray],
) -> dict[str, np.ndarray]:
    """Calculate future TCD_G and H/tau_x contribution projections."""
    pdo_recent = pdo_hist_rm21[-10:]
    amo_recent = amo_hist_rm21[-10:]

    pdo_combined = np.append(pdo_recent, pdo_future["mean"])
    pdo_combined_low = np.append(pdo_recent, pdo_future["low"])
    pdo_combined_high = np.append(pdo_recent, pdo_future["high"])

    # APJPT normalization is fixed from the historical 1920-2025 low-frequency series.
    apjpt_hist = amo_hist_rm21 * pdo_hist_rm21
    apjpt_mean = float(np.mean(apjpt_hist))
    apjpt_std = float(np.std(apjpt_hist, ddof=0))
    if not np.isfinite(apjpt_std) or apjpt_std == 0:
        raise ValueError("Historical APJPT standard deviation is zero/invalid.")

    # For target windows ending 2026-2035:
    # PDO(t), AMO(t-8), APJPT(t-4).
    pdo_for_tcd = pdo_future["mean"]
    amo_for_tcd = amo_combined[2:12]

    apjpt_combined = (pdo_combined * amo_combined - apjpt_mean) / apjpt_std
    apjpt_for_tcd = apjpt_combined[6:16]

    gwi_mean_future = gwi_rm21["rm21_mean"][10:]
    gwi_low_future = gwi_rm21["rm21_low"][10:]
    gwi_high_future = gwi_rm21["rm21_high"][10:]

    warming_mean = INTERCEPT_GWI + COEF_GWI * gwi_mean_future
    warming_low = np.minimum(
        INTERCEPT_GWI + COEF_GWI * gwi_low_future,
        INTERCEPT_GWI + COEF_GWI * gwi_high_future,
    )
    warming_high = np.maximum(
        INTERCEPT_GWI + COEF_GWI * gwi_low_future,
        INTERCEPT_GWI + COEF_GWI * gwi_high_future,
    )

    pdo_impact_mean = COEF_PDO * pdo_for_tcd
    amo_impact_mean = COEF_AMO * amo_for_tcd
    cross_impact_mean = COEF_APJPT * apjpt_for_tcd

    internal_mean = (
        INTERCEPT_INTERNAL
        + pdo_impact_mean
        + amo_impact_mean
        + cross_impact_mean
    )
    total_mean = warming_mean + internal_mean

    pdo_impact_low = np.minimum(
        COEF_PDO * pdo_future["low"],
        COEF_PDO * pdo_future["high"],
    )
    pdo_impact_high = np.maximum(
        COEF_PDO * pdo_future["low"],
        COEF_PDO * pdo_future["high"],
    )

    # AMO scenarios are deterministic; APJPT uncertainty is propagated from PDO.
    apjpt_low_raw = pdo_combined_low * amo_combined
    apjpt_high_raw = pdo_combined_high * amo_combined
    apjpt_low = (
        np.minimum(apjpt_low_raw, apjpt_high_raw) - apjpt_mean
    ) / apjpt_std
    apjpt_high = (
        np.maximum(apjpt_low_raw, apjpt_high_raw) - apjpt_mean
    ) / apjpt_std

    cross_low = np.minimum(
        COEF_APJPT * apjpt_low[6:16],
        COEF_APJPT * apjpt_high[6:16],
    )
    cross_high = np.maximum(
        COEF_APJPT * apjpt_low[6:16],
        COEF_APJPT * apjpt_high[6:16],
    )

    internal_low = (
        INTERCEPT_INTERNAL
        + pdo_impact_low
        + amo_impact_mean
        + cross_low
    )
    internal_high = (
        INTERCEPT_INTERNAL
        + pdo_impact_high
        + amo_impact_mean
        + cross_high
    )

    total_low = np.minimum(
        warming_low + internal_low,
        warming_high + internal_high,
    )
    total_high = np.maximum(
        warming_low + internal_low,
        warming_high + internal_high,
    )

    # Secondary projection: propagate TCD_G prediction uncertainty only.
    h_mean = INTERCEPT_H_ROLE + COEF_H_ROLE * (total_mean / 100.0)
    taux_mean = INTERCEPT_TAUX_ROLE + COEF_TAUX_ROLE * (total_mean / 100.0)

    h_from_low = INTERCEPT_H_ROLE + COEF_H_ROLE * (total_low / 100.0)
    h_from_high = INTERCEPT_H_ROLE + COEF_H_ROLE * (total_high / 100.0)
    taux_from_low = INTERCEPT_TAUX_ROLE + COEF_TAUX_ROLE * (total_low / 100.0)
    taux_from_high = INTERCEPT_TAUX_ROLE + COEF_TAUX_ROLE * (total_high / 100.0)

    h_low = np.minimum(h_from_low, h_from_high)
    h_high = np.maximum(h_from_low, h_from_high)
    taux_low = np.minimum(taux_from_low, taux_from_high)
    taux_high = np.maximum(taux_from_low, taux_from_high)

    return {
        "pdo_for_tcd": pdo_for_tcd,
        "amo_for_tcd": amo_for_tcd,
        "apjpt_for_tcd": apjpt_for_tcd,
        "warming_component": warming_mean,
        "pdo_component": pdo_impact_mean,
        "amo_component": amo_impact_mean,
        "apjpt_component": cross_impact_mean,
        "internal_component": internal_mean,
        "TCD_G_mean": total_mean,
        "TCD_G_low": total_low,
        "TCD_G_high": total_high,
        "H_role_mean": h_mean,
        "H_role_low": h_low,
        "H_role_high": h_high,
        "tau_x_role_mean": taux_mean,
        "tau_x_role_low": taux_low,
        "tau_x_role_high": taux_high,
    }


def plot_panel_c(
    ax_bar,
    historical: pd.DataFrame,
    future_year: np.ndarray,
    projection: dict[str, np.ndarray],
    title: str,
):
    """Plot historical/projected TCD_G and H/tau_x contributions."""
    width = 0.30

    hist_year = historical["end_year"].to_numpy(dtype=int)

    obs_h = ax_bar.bar(
        hist_year - width / 2,
        historical["contribution_H"].to_numpy(dtype=float) * 100,
        width=width,
        label="Obs. H role",
    )
    obs_taux = ax_bar.bar(
        hist_year + width / 2,
        historical["contribution_tau_x"].to_numpy(dtype=float) * 100,
        width=width,
        label=r"Obs. $\tau_x$ role",
    )

    h_yerr = np.vstack(
        [
            projection["H_role_mean"] - projection["H_role_low"],
            projection["H_role_high"] - projection["H_role_mean"],
        ]
    ) * 100
    taux_yerr = np.vstack(
        [
            projection["tau_x_role_mean"] - projection["tau_x_role_low"],
            projection["tau_x_role_high"] - projection["tau_x_role_mean"],
        ]
    ) * 100

    pred_h = ax_bar.bar(
        future_year - width / 2,
        projection["H_role_mean"] * 100,
        width=width,
        yerr=h_yerr,
        hatch="///",
        fill=False,
        capsize=2,
        label="Pred. H role",
    )
    pred_taux = ax_bar.bar(
        future_year + width / 2,
        projection["tau_x_role_mean"] * 100,
        width=width,
        yerr=taux_yerr,
        hatch="///",
        fill=False,
        capsize=2,
        label=r"Pred. $\tau_x$ role",
    )

    ax_tcd = ax_bar.twinx()

    obs_tcd, = ax_tcd.plot(
        hist_year,
        historical["TCD_G_mean_m"].to_numpy(dtype=float),
        linewidth=1.5,
        label="Obs. TCD_G mean",
    )
    ax_tcd.plot(
        [hist_year[-1], future_year[0]],
        [
            historical["TCD_G_mean_m"].iloc[-1],
            projection["TCD_G_mean"][0],
        ],
        linestyle="--",
        linewidth=1.2,
    )
    pred_tcd, = ax_tcd.plot(
        future_year,
        projection["TCD_G_mean"],
        linewidth=1.8,
        label="Pred. TCD_G mean",
    )
    ax_tcd.fill_between(
        future_year,
        projection["TCD_G_low"],
        projection["TCD_G_high"],
        alpha=0.22,
    )

    ax_bar.set_ylabel("21-year mean explained variance (%)")
    ax_bar.set_xlabel("Window-ending year")
    ax_bar.set_title(title, loc="left")
    ax_bar.set_xlim(1998, 2036)
    ax_bar.set_xticks(np.arange(2000, 2036, 5))
    ax_bar.set_ylim(0, 100)
    ax_bar.grid(True, linestyle=":", linewidth=0.6, alpha=0.6)

    ax_bar.legend(
        [obs_h, obs_taux, pred_h, pred_taux],
        ["Obs. H role", r"Obs. $\tau_x$ role", "Pred. H role", r"Pred. $\tau_x$ role"],
        frameon=False,
        fontsize=9,
        loc="upper left",
    )

    ax_tcd.set_ylabel("21-year running-mean TCD_G (m)")
    ax_tcd.legend(
        [obs_tcd, pred_tcd],
        ["Obs. TCD_G mean", "Pred. TCD_G mean"],
        frameon=False,
        fontsize=9,
        loc="upper center",
    )


def save_projection_source_data(
    path: Path,
    future_year: np.ndarray,
    projection: dict[str, np.ndarray],
    scenario: str,
):
    """Save one scenario's future projection source data."""
    df = pd.DataFrame(
        {
            "window_end_year": future_year,
            "AMO_scenario": scenario,
            "PDO": projection["pdo_for_tcd"],
            "AMO_lag8": projection["amo_for_tcd"],
            "APJPT_lag4": projection["apjpt_for_tcd"],
            "warming_component_m": projection["warming_component"],
            "PDO_component_m": projection["pdo_component"],
            "AMO_component_m": projection["amo_component"],
            "APJPT_component_m": projection["apjpt_component"],
            "internal_component_m": projection["internal_component"],
            "TCD_G_mean_m": projection["TCD_G_mean"],
            "TCD_G_low_m": projection["TCD_G_low"],
            "TCD_G_high_m": projection["TCD_G_high"],
            "H_role_mean": projection["H_role_mean"],
            "H_role_low": projection["H_role_low"],
            "H_role_high": projection["H_role_high"],
            "tau_x_role_mean": projection["tau_x_role_mean"],
            "tau_x_role_low": projection["tau_x_role_low"],
            "tau_x_role_high": projection["tau_x_role_high"],
        }
    )
    df.to_csv(path, index=False)


def main():
    parser = argparse.ArgumentParser(
        description="Reproduce Figure 4 and AMO-sensitivity projections."
    )
    parser.add_argument("--data-dir", default="data")
    parser.add_argument("--output-dir", default="outputs")
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    files = {
        "pdo_hist": data_dir / "pdo_index.1854-2025.nc",
        "amo_hist": data_dir / "AMO_index_1854-2025.nc",
        "pdo_future": data_dir / "future_10yr_pdo_prediction.csv",
        "amo_future": data_dir / "AMO_future_10yr_three_methods_wide.csv",
        "gwi_hist": data_dir / "global_warming_index_annual_raw.csv",
        "gwi_future": data_dir / "GWI_future_10yr_recent30_quadratic_with_uncertainty.csv",
        "figure1_source": data_dir / "Figure1_source_data.csv",
    }

    missing = [str(path) for path in files.values() if not path.exists()]
    if missing:
        raise FileNotFoundError(
            "Missing required Figure-4 input files:\n  - " + "\n  - ".join(missing)
        )

    # -------------------------------------------------------------------------
    # Historical PDO / AMO
    # -------------------------------------------------------------------------
    (
        hist_window_end,
        pdo_hist_rm21,
        amo_hist_rm21,
        recent_window_end,
    ) = build_historical_low_frequency_indices(
        files["pdo_hist"],
        files["amo_hist"],
    )

    pdo_recent = pdo_hist_rm21[-10:]
    amo_recent = amo_hist_rm21[-10:]

    # -------------------------------------------------------------------------
    # Future PDO / AMO
    # -------------------------------------------------------------------------
    pdo_future = read_pdo_future(files["pdo_future"])
    amo_future = read_amo_future(files["amo_future"])

    future_year = pdo_future["display_year"]
    if not np.array_equal(future_year, np.arange(2026, 2036)):
        print(
            "NOTE: future display years read from PDO forecast:",
            future_year,
        )

    amo_combined = {
        "persistence": np.append(amo_recent, amo_future["persistence"]),
        "damped": np.append(amo_recent, amo_future["damped"]),
        "recent_trend": np.append(amo_recent, amo_future["recent_trend"]),
    }

    # -------------------------------------------------------------------------
    # GWI
    # -------------------------------------------------------------------------
    gwi_hist_year, gwi_hist_value = read_gwi_history(files["gwi_hist"])
    gwi_fu_year, gwi_fu, gwi_fu_low, gwi_fu_high = read_gwi_future(
        files["gwi_future"]
    )
    gwi_rm21 = build_gwi_rm21(
        gwi_hist_year,
        gwi_hist_value,
        gwi_fu_year,
        gwi_fu,
        gwi_fu_low,
        gwi_fu_high,
    )

    # -------------------------------------------------------------------------
    # TCD_G projections
    # -------------------------------------------------------------------------
    projections = {
        key: calculate_projection(
            amo_series,
            pdo_hist_rm21,
            amo_hist_rm21,
            pdo_future,
            gwi_rm21,
        )
        for key, amo_series in amo_combined.items()
    }

    # -------------------------------------------------------------------------
    # Historical Figure-1 source data
    # -------------------------------------------------------------------------
    historical = read_historical_figure1_source(files["figure1_source"])

    # -------------------------------------------------------------------------
    # Main Figure 4
    # -------------------------------------------------------------------------
    fig = plt.figure(figsize=(13, 8), dpi=400)
    grid = plt.GridSpec(9, 11, wspace=0.9, hspace=0.2)

    # Panel a: PDO / AMO
    ax = fig.add_subplot(grid[0:5, 0:5])
    ax.plot(recent_window_end, pdo_recent, linewidth=2, label="Observed PDO")
    ax.plot(
        [recent_window_end[-1], future_year[0]],
        [pdo_recent[-1], pdo_future["mean"][0]],
        linestyle="--",
        linewidth=1.4,
    )
    ax.plot(
        future_year,
        pdo_future["mean"],
        linestyle="--",
        linewidth=2,
        label="Pred. PDO",
    )
    ax.fill_between(
        future_year,
        pdo_future["low"],
        pdo_future["high"],
        alpha=0.25,
    )

    ax_amo = ax.twinx()
    ax_amo.plot(recent_window_end, amo_recent, linewidth=2, label="Observed AMO")
    ax_amo.plot(
        [recent_window_end[-1], future_year[0]],
        [amo_recent[-1], amo_future["persistence"][0]],
        linestyle="--",
        linewidth=1.4,
    )
    ax_amo.plot(
        future_year,
        amo_future["persistence"],
        linestyle="--",
        linewidth=2,
        label="Pred. AMO",
    )

    ax.set_ylabel("21-year running-mean PDO index")
    ax_amo.set_ylabel("21-year running-mean AMO index")
    ax.set_xlabel("Window-ending year")
    ax.set_title("(a) Temporal variation of climate signals", loc="left")
    ax.set_xlim(2015, 2036)
    ax.set_xticks(np.arange(2015, 2036, 5))
    ax.grid(True, linestyle=":", linewidth=0.6, alpha=0.6)

    lines = ax.get_lines()[:2] + ax_amo.get_lines()[:2]
    labels = ["Observed PDO", "Pred. PDO", "Observed AMO", "Pred. AMO"]
    # Explicit handles avoid relying on twin-axis automatic legend merging.
    handles = [
        ax.lines[0],
        ax.lines[2],
        ax_amo.lines[0],
        ax_amo.lines[2],
    ]
    ax.legend(handles, labels, ncol=2, frameon=False, fontsize=9, loc="best")

    # Panel b: GWI
    ax_gwi = fig.add_subplot(grid[0:5, 6:])
    years = gwi_rm21["annual_year"]
    values = gwi_rm21["annual_mean"]
    low = gwi_rm21["annual_low"]
    high = gwi_rm21["annual_high"]

    hist_mask = years <= 2025
    future_mask = years > 2025

    ax_gwi.plot(years[hist_mask], values[hist_mask], linewidth=1.5, label="Observed GWI")
    fit_coef = np.polyfit(gwi_hist_year.astype(float), gwi_hist_value.astype(float), 2)
    ax_gwi.plot(
        gwi_hist_year,
        np.polyval(fit_coef, gwi_hist_year),
        linewidth=1.5,
        label="GWI trend",
    )
    if np.any(future_mask):
        ax_gwi.plot(
            [years[hist_mask][-1], years[future_mask][0]],
            [values[hist_mask][-1], values[future_mask][0]],
            linestyle="--",
            linewidth=1.2,
        )
        ax_gwi.plot(
            years[future_mask],
            values[future_mask],
            linestyle="--",
            linewidth=1.5,
            label="Pred. GWI",
        )
        ax_gwi.fill_between(
            years[future_mask],
            low[future_mask],
            high[future_mask],
            alpha=0.2,
        )

    ax_gwi.set_ylabel("Global warming index (°C)")
    ax_gwi.set_xlabel("Year")
    ax_gwi.set_title("(b) Temporal variation of GWI", loc="left")
    ax_gwi.set_xlim(1995, 2036)
    ax_gwi.set_xticks(np.arange(1995, 2036, 5))
    ax_gwi.grid(True, linestyle=":", linewidth=0.6, alpha=0.6)
    ax_gwi.legend(frameon=False, fontsize=9, loc="upper left")

    # Panel c
    ax_c = fig.add_subplot(grid[6:, :])
    plot_panel_c(
        ax_c,
        historical,
        future_year,
        projections["persistence"],
        "(c) Variation of TCD_G and projected ENSO precursor contributions",
    )

    fig.subplots_adjust(hspace=0.3, wspace=0.5)
    fig.savefig(output_dir / "Figure4.png", dpi=400, bbox_inches="tight")
    fig.savefig(output_dir / "Figure4.pdf", bbox_inches="tight")
    plt.close(fig)

    # -------------------------------------------------------------------------
    # Supplementary AMO sensitivity
    # -------------------------------------------------------------------------
    fig = plt.figure(figsize=(13, 6.6), dpi=400)
    grid = plt.GridSpec(2, 1, hspace=0.38)

    ax1 = fig.add_subplot(grid[0, 0])
    plot_panel_c(
        ax1,
        historical,
        future_year,
        projections["damped"],
        "(a) AMO damped-persistence scenario",
    )

    ax2 = fig.add_subplot(grid[1, 0])
    plot_panel_c(
        ax2,
        historical,
        future_year,
        projections["recent_trend"],
        "(b) AMO recent-linear-trend scenario",
    )

    fig.savefig(
        output_dir / "Appendix_AMO_sensitivity.png",
        dpi=400,
        bbox_inches="tight",
    )
    fig.savefig(
        output_dir / "Appendix_AMO_sensitivity.pdf",
        bbox_inches="tight",
    )
    plt.close(fig)

    # -------------------------------------------------------------------------
    # Source data
    # -------------------------------------------------------------------------
    save_projection_source_data(
        output_dir / "Figure4_projection_source_data.csv",
        future_year,
        projections["persistence"],
        "persistence",
    )
    save_projection_source_data(
        output_dir / "Appendix_AMO_damped_source_data.csv",
        future_year,
        projections["damped"],
        "damped_persistence",
    )
    save_projection_source_data(
        output_dir / "Appendix_AMO_recent_trend_source_data.csv",
        future_year,
        projections["recent_trend"],
        "recent_linear_trend",
    )

    panel_a_source = pd.DataFrame(
        {
            "window_end_year": np.append(recent_window_end, future_year),
            "PDO_mean": np.append(pdo_recent, pdo_future["mean"]),
            "PDO_low": np.append(pdo_recent, pdo_future["low"]),
            "PDO_high": np.append(pdo_recent, pdo_future["high"]),
            "AMO_persistence": np.append(amo_recent, amo_future["persistence"]),
        }
    )
    panel_a_source.to_csv(
        output_dir / "Figure4_panel_a_source_data.csv",
        index=False,
    )

    panel_b_source = pd.DataFrame(
        {
            "year": years,
            "GWI_mean": values,
            "GWI_low": low,
            "GWI_high": high,
        }
    )
    panel_b_source.to_csv(
        output_dir / "Figure4_panel_b_source_data.csv",
        index=False,
    )

    print("Figure 4 reproduction completed.")
    print("Outputs written to:", output_dir.resolve())


if __name__ == "__main__":
    main()
